/* a lexical analyzer system for simple */

#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>

/* Global declarations */

int charClass;
char lexeme [100];
double tokenValue;
char nextChar;
int lexLen;
int token;
int nextToken;
FILE *in_fp, *fopen();

/* Function declarations */
void addChar();
void getChar();
void getNonBlank();
double expr();
double factor();
double term();
int lex();

/* Character classes*/
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26

/******************************/

int main(){
    if ((in_fp = fopen("front.in", "r")) == NULL)
        printf("ERROR - cannot open front.in \n");
    else {
        getChar();
        do {
        lex();
        printf("ans = %lf\n", expr());
        } while (nextToken != EOF);
    }
}

void error(){
    printf("some thing worring");
}

int lookup(char ch){
    switch (ch){
        case '(':
            addChar();
            nextToken = LEFT_PAREN;
            break;
        case ')':
            addChar();
            nextToken = RIGHT_PAREN;
            break;
        case '+':
            addChar();
            nextToken = ADD_OP;
            break;
        case '-':
            addChar();
            nextToken = SUB_OP;
            break;
        case '*':
            addChar();
            nextToken = MULT_OP;
            break;

        case '/':
            addChar();
            nextToken = DIV_OP;
            break;

        default:
            addChar();
            nextToken = EOF;
            break;
    }
    return nextToken;
}

void addChar(){
    if (lexLen <= 98) {
        lexeme[lexLen++] = nextChar;
        lexeme[lexLen] = '\0';
    }
    else
        printf("Error - lexeme is too long \n");
}

void getChar() {
    if ((nextChar = getc(in_fp)) != EOF) {
        if (isalpha(nextChar))
            charClass = LETTER;
        else if (isdigit(nextChar))
            charClass = DIGIT;
        else charClass  = UNKNOWN;
    }
    else
        charClass = EOF;
}

 void getNonBlank() { 
    while (isspace(nextChar))
        getChar();
 }

int lex() {
    lexLen = 0;
    getNonBlank();
    switch (charClass){
        case LETTER:
            addChar();
            getChar();
            while (charClass == LETTER || charClass == DIGIT) {
                addChar();
                getChar();
            }

        nextToken  = IDENT;
        break;

        case DIGIT:
          addChar();
          getChar();
          while (charClass == DIGIT) {
              addChar();
              getChar();
          }
          nextToken = INT_LIT;
          break;

        case UNKNOWN:
          lookup(nextChar);
          getChar();
          break;

        case EOF:
          nextToken = EOF;
          lexeme[0] = 'E';
          lexeme[1] = 'O';
          lexeme[2] = 'F';
          lexeme[3] = 0;
          break;
    }
    if (nextToken == INT_LIT) {
        sscanf(lexeme, "%lf", &tokenValue);
    }
    /* printf("Next token is: %d, Next lexeme is %s tokenValue %lf\n", nextToken, lexeme, tokenValue); */
    return nextToken;
}


/* Expr */ 
/* parses string in the language generated by the rule: */
/* <expr> -> <term> { (+ | -) <term>} */

double expr(){
   /* printf ("Enter <expr>\n"); */
    double v1;
    double v2;
    v1 = term();

    while(nextToken == ADD_OP || nextToken == SUB_OP) {
        if (nextToken == ADD_OP) {
            lex();
            v2 = term();
            v1 += v2;

        } else {
            lex();
            v2 = term();
            v1 -= v2;
        }
    }
    /* printf("Exit <expr>\n"); */
    return v1;
}

/* term */
/* Parses string in the language generated by the rule: */
/* <term> -> <factor> { (* | /) <factor>} */

double term(){
    double v1;
    double v2;
    /* printf("Enter <term>\n"); */
    v1 = factor();

    while(nextToken == MULT_OP || nextToken == DIV_OP) {
        if (nextToken == MULT_OP){
          lex();
          v2 = factor();
          v1 *= v2;
        }else {
            lex();
            v2 = factor();
            v1 /= v2;
        }
    }
    /* printf("Exit <term>\n"); */
    return v1;
}

/* factor */
/* parses string in the language generated by the rule: */
/* <factor> -> id | int_constant | ( <expr) */

double factor() {
    /* printf("Enter <factor>\n"); */

    if (nextToken == IDENT || nextToken == INT_LIT){
        lex();
        return tokenValue;
    }
    /* printf("Exit <factor>\n"); */
    return 0.0;
}
